### ISSUE TITLE
scheduler extender

### ISSUE THREAD

**Issue by llhuii** [llhuii/dive-into-k8s#16]
[scheduler extender](https://github.com/kubernetes/design-proposals-archive/blob/main/scheduling/scheduler_extender.md)

kube-scheduler增加
```
--policy-config-file=/etc/kubernetes/config/scheduler-policy-config.yaml
```

policy-config.yaml:
```yaml
apiVersion: v1
kind: Policy
hardPodAffinitySymmetricWeight: 10
extenders:
- Ignorable: true
  bindVerb: ''
  enableHttps: false
  filterVerb: 'predicates'
  nodeCacheCapable: true
  preemptVerb: ''
  prioritizeVerb: priorities
  urlPrefix: http://scheduler-extender-service:23000/scheduler
  weight: 10
- Ignorable: true
  bindVerb: ''
  enableHttps: false
  filterVerb: predicates
  nodeCacheCapable: true
  preemptVerb: ''
  prioritizeVerb: ''
  urlPrefix: http://scheduler-service:24000/scheduler
  weight: 10
```
